# Insights Service Approval APIs
#
# APIs to query approval service
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#
module Api
  module V0
    class ApproversController < ApplicationController
      include ApproverOperationsMixin
    end
  end
end
