=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do

  mount SwaggerUiEngine::Engine, at: '/api'

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    constraint = opts[:constraint_name].camelize.constantize

    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", constraints: constraint, via: http_method
  end

  add_swagger_route 'POST', '/stages/{stage_id}/actions', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'add_action'
  add_swagger_route 'POST', '/groups', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'add_group'
  add_swagger_route 'POST', '/requests/{request_id}/stages', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'add_stage'
  add_swagger_route 'POST', '/templates', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'add_template'
  add_swagger_route 'POST', '/templates/{template_id}/workflows', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'add_workflow'
  add_swagger_route 'GET', '/actions/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_action_by_id'
  add_swagger_route 'GET', '/actions', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_actions'
  add_swagger_route 'GET', '/groups/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_group_by_id'
  add_swagger_route 'GET', '/groups', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_groups'
  add_swagger_route 'GET', '/requests', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_requests'
  add_swagger_route 'GET', '/stages/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_stage_by_id'
  add_swagger_route 'GET', '/stages', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_stages'
  add_swagger_route 'GET', '/templates/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_template_by_id'
  add_swagger_route 'GET', '/templates/{template_id}/workflows', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_template_workflows'
  add_swagger_route 'GET', '/templates', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_templates'
  add_swagger_route 'GET', '/workflows/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_workflow_by_id'
  add_swagger_route 'GET', '/workflows/{workflow_id}/requests', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_workflow_requests'
  add_swagger_route 'GET', '/workflows', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'fetch_workflows'
  add_swagger_route 'DELETE', '/actions/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'remove_action'
  add_swagger_route 'DELETE', '/groups/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'remove_group'
  add_swagger_route 'DELETE', '/requests/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'remove_request'
  add_swagger_route 'DELETE', '/stages/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'remove_stage'
  add_swagger_route 'DELETE', '/templates/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'remove_template'
  add_swagger_route 'DELETE', '/workflows/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'remove_workflow'
  add_swagger_route 'PUT', '/actions/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'update_action'
  add_swagger_route 'PUT', '/groups/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'update_group'
  add_swagger_route 'PUT', '/requests/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'update_request'
  add_swagger_route 'PUT', '/stages/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'update_stage'
  add_swagger_route 'PUT', '/templates/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'update_template'
  add_swagger_route 'PUT', '/workflows/{id}', controller_name: 'admins', constraint_name: 'adminsConstraint', action_name: 'update_workflow'
  add_swagger_route 'POST', '/stages/{stage_id}/actions', controller_name: 'approvers', constraint_name: 'approversConstraint', action_name: 'add_action'
  add_swagger_route 'GET', '/actions/{id}', controller_name: 'approvers', constraint_name: 'approversConstraint', action_name: 'fetch_action_by_id'
  add_swagger_route 'GET', '/actions', controller_name: 'approvers', constraint_name: 'approversConstraint', action_name: 'fetch_actions'
  add_swagger_route 'GET', '/stages/{id}', controller_name: 'approvers', constraint_name: 'approversConstraint', action_name: 'fetch_stage_by_id'
  add_swagger_route 'DELETE', '/actions/{id}', controller_name: 'approvers', constraint_name: 'approversConstraint', action_name: 'remove_action'
  add_swagger_route 'PUT', '/actions/{id}', controller_name: 'approvers', constraint_name: 'approversConstraint', action_name: 'update_action'
  add_swagger_route 'PUT', '/stages/{id}', controller_name: 'approvers', constraint_name: 'approversConstraint', action_name: 'update_stage'
  add_swagger_route 'POST', '/workflows/{workflow_id}/requests', controller_name: 'users', constraint_name: 'usersConstraint', action_name: 'add_request'
  add_swagger_route 'GET', '/requests/{id}', controller_name: 'users', constraint_name: 'usersConstraint', action_name: 'fetch_request_by_id'
  add_swagger_route 'GET', '/requests/{request_id}/stages', controller_name: 'users', constraint_name: 'usersConstraint', action_name: 'fetch_request_stages'
end
