=begin
Service Catalog Approval Service APIs

Service catalog approval service APIs

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration[5.1]
  def change
    create_table "group".pluralize.to_sym, id: :serial do |t|
      t.string :name
      t.string :email
      t.string :action
      t.string :message

      t.timestamps
    end

    create_table "template".pluralize.to_sym, id: :serial do |t|
      t.string :description
      t.string :title
      t.string :created_by

      t.timestamps
    end

    create_table "workflow".pluralize.to_sym, id: :serial do |t|
      t.string :name
      t.string :groups
      t.references :template, foreign_key: true

      t.timestamps
    end

    create_table "request".pluralize.to_sym, id: :serial do |t|
      t.string :uuid
      t.string :name
      t.string :requested_by
      t.string :state
      t.string :status
      t.string :content
      t.references :workflow, foreign_key: true

      t.timestamps
    end
  end
end
