=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration[5.1]
  def change
    create_table "action".pluralize.to_sym do |t|
      t.string :processed_by
      t.datetime :actioned_at
      t.datetime :notified_at
      t.string :decision
      t.string :comments
      t.references :stage

      t.timestamps
    end

    create_table "group".pluralize.to_sym do |t|
      t.string :name
      t.string :contact_method
      t.jsonb  :contact_setting

      t.timestamps
    end

    create_table "template".pluralize.to_sym do |t|
      t.string :title
      t.string :description
      t.string :ext_ref

      t.timestamps
    end

    create_table "workflow".pluralize.to_sym do |t|
      t.string :name
      t.string :description
      t.references :template, foreign_key: true

      t.timestamps
    end

    create_table "workflowgroup".pluralize.to_sym do |t|
      t.references :workflow, foreign_key: true
      t.references :group, foreign_key: true
    end

    create_table "request".pluralize.to_sym do |t|
      t.string :requester
      t.string :name
      t.string :description
      t.string :state
      t.string :decision
      t.string :reason
      t.jsonb  :content
      t.references :workflow, foreign_key: true

      t.timestamps
    end

    create_table "stage".pluralize.to_sym do |t|
      t.string :state
      t.string :decision
      t.string :comments
      t.references :group, foreign_key: true
      t.references :request, foreign_key: true

      t.timestamps
    end
  end
end
