=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class AdminsController < ApplicationController
  include UserOperationsMixin
  include ApproverOperationsMixin

  def add_group
    group = Group.create!(group_params)
    json_response(group, :created)
  end

  def add_stage
    req = Request.find(params[:request_id])
    stage = req.stages.create!(stage_params)

    json_response(stage, :created)
  end

  def add_template
    template = Template.create!(template_params)
    json_response(template, :created)
  end

  def add_workflow
    workflow = Template.find(params[:template_id]).workflows.create!(workflow_params)
    json_response(workflow, :created)
  end

  def fetch_group_by_id
    group = Group.find(params[:id])

    json_response(group)
  end

  def fetch_groups
    groups = Group.all

    json_response(groups)
  end

  def fetch_requests
    reqs = Request.filter(params.slice(:requester, :decision, :state))

    json_response(reqs)
  end

  def fetch_stages
    stages = Stage.all

    json_response(stages)
  end

 def fetch_template_by_id
    template = Template.find(params[:id])
    json_response(template)
  end

  def fetch_template_workflows
    template = Template.find(params[:template_id])
    json_response(template.workflows)
  end

  def fetch_templates
    templates = Template.all
    json_response(templates)
  end

  def fetch_workflow_by_id
    workflow = Workflow.find(params[:id])

    json_response(workflow)
  end

  def fetch_workflow_requests
    workflow = Workflow.find(params[:workflow_id])

    json_response(workflow.requests)
  end

  def fetch_workflows
    workflows = Workflow.all

    json_response(workflows)
  end

  def remove_group
    Group.find(params[:id]).destroy
    head :no_content
  end

  def remove_request
    Request.find(params[:id]).destroy
    head :no_content
  end

  def remove_stage
    Stage.find(params[:id]).destroy
    head :no_content
  end

  def remove_template
    Template.find(params[:id]).destroy
  end

  def remove_workflow
    Workflow.find(params[:id]).destroy

    head :no_content
  end

  def update_group
    Group.find(params[:id]).update(group_params)
    head :no_content
  end

  def update_request
    RequestUpdateService.new(params[:id]).update(request_params)
    head :no_content
  end

  def update_template
    Template.find(params[:id]).update(template_params)
    head :no_content
  end

  def update_workflow
    Workflow.find(params[:id]).update(workflow_params)

    head :no_content
  end

  private

  def group_params
    params.permit(:name, :contact_method, :contact_setting)
  end

  def stage_params
    params.permit(:state, :decision, :comments, :group_id)
  end

  def template_params
    params.permit(:title, :description)
  end

  def workflow_params
    params.permit(:name, :description)
  end

  def request_params
    params.permit(:name, :decision, :state, :requester, :content)
  end
end
