=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Action < ApplicationRecord
  acts_as_tenant(:tenant)

  include ApprovalDecisions

  validates_inclusion_of :decision, :in => DECISIONS
  validates_presence_of :processed_by
  belongs_to :stage
end
