=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Action < ApplicationRecord
  acts_as_tenant(:tenant)

  NOTIFY_OPERATION  = 'notify'.freeze
  SKIP_OPERATION    = 'skip'.freeze
  MEMO_OPERATION    = 'memo'.freeze
  APPROVE_OPERATION = 'approve'.freeze
  DENY_OPERATION    = 'deny'.freeze
  OPERATIONS = [NOTIFY_OPERATION, SKIP_OPERATION, MEMO_OPERATION, APPROVE_OPERATION, DENY_OPERATION].freeze

  validates :operation,    :inclusion => { :in => OPERATIONS }
  validates :processed_by, :presence  => true
  belongs_to :stage
end
