=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Group < ApplicationRecord
  acts_as_tenant(:tenant)

  validates :name,            :presence => true
  validates :contact_method,  :presence => true
  validates :contact_setting, :presence => true

  has_many :stages,         :dependent => :destroy
  has_many :workflowgroups, :dependent => :destroy
  has_many :workflows,      :through => :workflowgroups
end
