=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Group < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :contact_method
  validates_presence_of :contact_setting

  has_many :stages
  has_many :workflowgroups
  has_many :workflows, through: :workflowgroups
end
