=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class Request < ApplicationRecord
  include Filterable

  validates_presence_of :requester
  validates_presence_of :name
  validates_presence_of :content


  belongs_to :workflow
  has_many :stages

  validates_inclusion_of :state, :in => [ "pending", "skipped", "notified", "finished" ]
  validates_inclusion_of :decision, :in => [ "unknown", "approved", "denied" ]

  PENDING_STATE   = "pending".freeze
  SKIPPED_STATE   = "skipped".freeze
  NOTIFIED_STATE  = "notified".freeze
  FINISHED_STATE  = "finished".freeze
  STATES = [ PENDING_STATE, SKIPPED_STATE, NOTIFIED_STATE, FINISHED_STATE ].freeze

  UNKNOWN_STATUS  = "unknown".freeze
  APPROVED_STATUS = "approved".freeze
  DENIED_STATUS   = "denied".freeze
  DECISIONS = [ UNKNOWN_STATUS, APPROVED_STATUS, DENIED_STATUS ].freeze

  scope :decision, -> (decision) { where decision: decision }
  scope :state, -> (state) { where state: state }
  scope :requester, -> (requester) { where requester: requester }

  def self.valid_request_states
    STATES
  end

  def self.valid_request_decisions
    DECISIONS
  end
end
