=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class Request < ApplicationRecord
  include Filterable
  include ApprovalStates
  include ApprovalDecisions

  belongs_to :workflow
  has_many :stages

  validates_presence_of :requester
  validates_presence_of :name
  validates_presence_of :content

  validates_inclusion_of :state, :in => STATES
  validates_inclusion_of :decision, :in => DECISIONS

  scope :decision, ->(decision) { where decision: decision }
  scope :state, ->(state) { where state: state }
  scope :requester, ->(requester) { where requester: requester }
end
