=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Stage < ApplicationRecord

  has_many :actions
  belongs_to :group
  belongs_to :request
end
