=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Stage < ApplicationRecord
  include ApprovalStates
  include ApprovalDecisions

  has_many :actions
  belongs_to :group
  belongs_to :request

  validates_inclusion_of :state, :in => STATES
  validates_inclusion_of :decision, :in => DECISIONS
end
