=begin
Insights Service Approval APIs

APIs to query approval service

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Template < ApplicationRecord
  acts_as_tenant(:tenant)

  has_many :workflows

  validates :title, :presence => :title
end
