# Insights Service Approval APIs
#
# APIs to query approval service
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

class Workflow < ApplicationRecord
  acts_as_tenant(:tenant)

  belongs_to :template
  has_many :requests, :inverse_of => :workflow
  has_many :workflowgroups, :dependent => :destroy
  has_many :groups, -> { order(:id => :asc) }, :through => :workflowgroups

  validates :name, :presence => :name

  def as_json(_options = {})
    super(:methods => [:group_ids])
  end
end
